// let priv = localStorage.getItem("priv");


// export const mainMenu = ()=>{
//  let includesDashboard= priv.includes("1")
//  let includesResData= priv.includes("2")
//  let includesEatData= priv.includes("3")
//  let includesHealthData= priv.includes("4")
//  let includesHospData= priv.includes("5")
//  let includesMarketData= priv.includes("6")
//  let includesIndustryData= priv.includes("7")
//  let includesInstitutionData= priv.includes("8")
//  let includesSanitaryData= priv.includes("9")
//  let includesReports= priv.includes("10")
//  let includesSanitationReport= priv.includes("11")
//  let includesNotifications= priv.includes("12")
//  let includesSingleSMS= priv.includes("13")
//  let includesBulkSMS= priv.includes("14")
//  let includesSingleNotification= priv.includes("15")
//  let includesBulkNotification= priv.includes("16")
//  let includesBulkUploadDistrictData= priv.includes("17")
//  let includesBulkUploadElectoralAreaData= priv.includes("18")
//  let includesBulkUploadCommunityData= priv.includes("19")
//  let includesAddSingleDistrict= priv.includes("20")
//  let includesAddSingleElectoralArea= priv.includes("21")
//  let includesAddSingleCommunity= priv.includes("22")
//  let includesTransferDataOwnership= priv.includes("23")
//  let includesUserGuide= priv.includes("24")
//  let includesUser= priv.includes("25")
//  let includesUserLog= priv.includes("26")
//  let includesUserType= priv.includes("27")
// };
