export const district = [
  {
    id: 1,
    name: "Ablekuma Central",
    abbrv: "ABCMA",
    regionId: 7,
  },
  {
    id: 2,
    name: "Ablekuma North",
    abbrv: "ABNMA",
    regionId: 7,
  },
  { id: 3, name: "Ablekuma West", abbrv: "ABWMA", regionId: 7},
  { id: 4, name: "Accra", abbrv: "ACCMA", regionId: 7},
  { id: 5, name: "Ada East", abbrv: "ADEMA", regionId: 7},
  { id: 6, name: "Ada West", abbrv: "ADWMA", regionId: 7},
  { id: 7, name: "Adenta", abbrv: "ADTMA", regionId: 7},
  { id: 8, name: "Ashaiman", abbrv: "ASHMA", regionId: 7},
  { id: 9, name: "Ayawaso Central", abbrv: "AYCMA", regionId: 7},
  { id: 10, name: "Ayawaso East", abbrv: "AYEMA", regionId: 7},
  { id: 11, name: "Ayawaso North", abbrv: "AYNMA", regionId: 7},
  { id: 12, name: "Ayawaso West", abbrv: "AYWMA", regionId: 7},
  { id: 13, name: "Ga Central", abbrv: "GACMA", regionId: 7},
  { id: 14, name: "Ga East", abbrv: "GAEMA", regionId: 7},

  { id: 15, name: "Ga North", abbrv: "GANMA", regionId: 7},
  { id: 16, name: "Ga South", abbrv: "GASMA", regionId: 7},
  { id: 17, name: "Ga West", abbrv: "GAWMA", regionId: 7},
  { id: 18, name: "Korle-Klottey", abbrv: "KKLMA", regionId: 7},
  { id: 19, name: "Kpone-Katamanso", abbrv: "KPKMA", regionId: 7},
  { id: 20, name: "Krowor", abbrv: "KWRMA", regionId: 7},
  { id: 21, name: "La-Dade-Kotopon", abbrv: "LDKMA", regionId: 7},
  { id: 22, name: "La-Nkwantanang-Madina", abbrv: "LNMMA", regionId: 7},
  { id: 23, name: "Ledzokuku", abbrv: "LZKMA", regionId: 7},

  { id: 24, name: "Ningo-Prampram", abbrv: "NGPMA", regionId: 7},
  { id: 25, name: "Okaikwei North", abbrv: "OKNMA", regionId: 7},
  { id: 26, name: "Shai-Osudoku", abbrv: "SHOMA", regionId: 7},
  { id: 27, name: "Tema Metropolitan", abbrv: "TEMMA", regionId: 7},
  { id: 28, name: "Tema West", abbrv: "TMWMA", regionId: 7},
  { id: 29, name: "Weija Gbawe", abbrv: "WJGMA", regionId: 7},
  { id: 30, name: "Adansi Asokwa", abbrv: "ADKMA", regionId: 2 },
  { id: 31, name: "Adansi North", abbrv: "ADNMA", regionId: 2 },
  { id: 32, name: "Adansi South", abbrv: "ADSMA", regionId: 2 },
  { id: 33, name: "Afigya-Kwabre North", abbrv: "AKNMA", regionId: 2 },
  { id: 34, name: "Afigya-Kwabre South", abbrv: "AKSMA", regionId: 2 },
  { id: 35, name: "Ahafo-Ano North", abbrv: "AANMA", regionId: 2 },
  { id: 36, name: "Ahafo-Ano South East", abbrv: "ASEMA", regionId: 2 },
  { id: 37, name: "Ahafo-Ano South West", abbrv: "ASWMA", regionId: 2 },
  { id: 38, name: "Akrofuom", abbrv: "AKFMA", regionId: 2 },
  { id: 39, name: "Amansie Central", abbrv: "AMCDA", regionId: 2 },
  { id: 40, name: "Amansie West", abbrv: "AMWDA", regionId: 2 },
  { id: 41, name: "Amansie South", abbrv: "AMSDA", regionId: 2 },
  { id: 42, name: "Asante-Akim Central", abbrv: "AACMA", regionId: 2 },
  { id: 43, name: "Asante-Akim North", abbrv: "AANDA", regionId: 2 },
  { id: 44, name: "Asante-Akim South", abbrv: "AASDA", regionId: 2 },
  { id: 45, name: "Asokore-Mampong", abbrv: "ASMDA", regionId: 2 },
  { id: 46, name: "Asokwa", abbrv: "ASKMA", regionId: 2 },
  { id: 47, name: "Atwima-Kwanwoma", abbrv: "ATKMA", regionId: 2 },
  { id: 48, name: "Atwima-Mponua", abbrv: "ATMMA", regionId: 2 },
  { id: 49, name: "Atwima-Nwabiagya", abbrv: "ATNMA", regionId: 2 },
  { id: 50, name: "Atwima-Nwabiagya North", abbrv: "ANNMA", regionId: 2 },
  { id: 51, name: "Bekwai", abbrv: "BEKMA", regionId: 2 },
  { id: 52, name: "Bosome Freho", abbrv: "BSFMA", regionId: 2 },
  { id: 53, name: "Bosomtwe", abbrv: "BSTMA", regionId: 2 },
  { id: 54, name: "Ejisu", abbrv: "EJSMA", regionId: 2 },
  { id: 55, name: "Ejura/Sekyedumase", abbrv: "EJRMA", regionId: 2 },
  { id: 56, name: "Juaben", abbrv: "JBNMA", regionId: 2 },
  { id: 57, name: "Kumasi", abbrv: "KSIMA", regionId: 2 },
  { id: 58, name: "Kwabre East", abbrv: "KWEMA", regionId: 2 },
  { id: 59, name: "Kwadaso", abbrv: "KWDMA", regionId: 2 },
  { id: 60, name: "Mampong", abbrv: "MPGMA", regionId: 2 },
  { id: 61, name: "Obuasi East", abbrv: "OBEMA", regionId: 2 },
  { id: 62, name: "Obuasi", abbrv: "OBSMA", regionId: 2 },
  { id: 63, name: "Offinso", abbrv: "OFSMA", regionId: 2 },
  { id: 64, name: "Offinso North", abbrv: "OFNMA", regionId: 2 },
  { id: 65, name: "Oforikrom", abbrv: "OFKMA", regionId: 2 },
  { id: 66, name: "Old Tafo", abbrv: "OTFMA", regionId: 2 },
  { id: 67, name: "Sekyere Afram Plains", abbrv: "SAPMA", regionId: 2 },
  { id: 68, name: "Sekyere Central", abbrv: "SYCMA", regionId: 2 },
  { id: 69, name: "Sekyere East", abbrv: "SYEMA", regionId: 2 },
  { id: 70, name: "Sekyere Kumawu", abbrv: "SYKMA", regionId: 2 },
  { id: 71, name: "Sekyere South", abbrv: "SYSMA", regionId: 2 },
  { id: 72, name: "Suame", abbrv: "SMEMA", regionId: 2 },
];
