export const district = [
  {
    id: 1,
    name: "Ablekuma Central",
    abbrv: "",
    regionId: 1,
  },
  {
    id: 2,
    name: "Ablekuma North",
    abbrv: "",
    regionId: 1,
  },
  { id: 3, name: "Ablekuma West", abbrv: "", regionId: 1 },
  { id: 4, name: "Accra", abbrv: "AMA", regionId: 1 },
  { id: 5, name: "Ada East", abbrv: "", regionId: 1 },
  { id: 6, name: "Ada West", abbrv: "", regionId: 1 },
  { id: 7, name: "Adenta", abbrv: "", regionId: 1 },
  { id: 8, name: "Ashaiman", abbrv: "", regionId: 1 },
  { id: 9, name: "Ayawaso Central", abbrv: "", regionId: 1 },
  { id: 10, name: "Ayawaso East", abbrv: "", regionId: 1 },
  { id: 11, name: "Ayawaso North", abbrv: "", regionId: 1 },
  { id: 12, name: "Ayawaso West", abbrv: "", regionId: 1 },
  { id: 13, name: "Ga Central", abbrv: "", regionId: 1 },
  { id: 14, name: "Ga East", abbrv: "", regionId: 1 },

  { id: 15, name: "Ga North", abbrv: "", regionId: 1 },
  { id: 16, name: "Ga South", abbrv: "", regionId: 1 },
  { id: 17, name: "Ga West", abbrv: "", regionId: 1 },
  { id: 18, name: "Korle-Klottey", abbrv: "", regionId: 1 },
  { id: 19, name: "Kpone-Katamanso", abbrv: "", regionId: 1 },
  { id: 20, name: "Krowor", abbrv: "", regionId: 1 },
  { id: 21, name: "La-Dade-Kotopon", abbrv: "", regionId: 1 },
  { id: 22, name: "La-Nkwantanang-Madina", abbrv: "", regionId: 1 },
  { id: 23, name: "Ledzokuku", abbrv: "", regionId: 1 },

  { id: 24, name: "Ningo-Prampram", abbrv: "", regionId: 1 },
  { id: 25, name: "Okaikwei North", abbrv: "", regionId: 1 },
  { id: 26, name: "Shai-Osudoku", abbrv: "", regionId: 1 },
  { id: 27, name: "Tema Metropolitan", abbrv: "", regionId: 1 },
  { id: 28, name: "Tema West", abbrv: "", regionId: 1 },
  { id: 29, name: "Weija Gbawe", abbrv: "", regionId: 1 },
  { id: 30, name: "Adansi Asokwa", abbrv: "", regionId: 2 },
  { id: 31, name: "Adansi North", abbrv: "", regionId: 2 },
  {id:32,
    name: "Adansi South",
    abbrv: "",
    regionId: 2,
  },
  {id: 33,
    name: "Afigya-Kwabre North",
    abbrv: "",
    regionId: 2,
  },
  {id: 34,
    name: "Afigya-Kwabre South",
    abbrv: "",
    regionId: 2,
  },
  {id:35,
    name: "Ahafo-Ano North",
    abbrv: "",
    regionId: 2,
  },
  {id:36,
    name: "Ahafo-Ano South East",
    abbrv: "",
    regionId: 2,
  },
  {id:37,
    name: "Ahafo-Ano South West",
    abbrv: "",
    regionId: 2,
  },
  {id:38,
    name: "Akrofuom",
    abbrv: "",
    regionId: 2,
  },
  {id:39,
    name: "Amansie Central",
    abbrv: "",
    regionId: 2,
  },
  {id:40,
    name: "Amansie West",
    abbrv: "",
    regionId: 2,
  },
  {id:41,
    name: "Amansie South",
    abbrv: "",
    regionId: 2,
  },
  {id:42,
    name: "Asante-Akim Central",
    abbrv: "",
    regionId: 2,
  },
  {id:43,
    name: "Asante-Akim North",
    abbrv: "",
    regionId: 2,
  },
  {id:44,
    name: "Asante-Akim South",
    abbrv: "",
    regionId: 2,
  },
  {id:45,
    name: "Asokore-Mampong",
    abbrv: "",
    regionId: 2,
  },
  {id:46,
    name: "Asokwa",
    abbrv: "",
    regionId: 2,
  },
  {id:47,
    name: "Atwima-Kwanwoma",
    abbrv: "",
    regionId: 2,
  },
  {id:48,
    name: "Atwima-Mponua",
    abbrv: "",
    regionId: 2,
  },
  {id:49,
    name: "Atwima-Nwabiagya",
    abbrv: "",
    regionId: 2,
  },
  {id:50,
    name: "Atwima-Nwabiagya North",
    abbrv: "",
    regionId: 2,
  },
  {id:51,
    name: "Bekwai",
    abbrv: "",
    regionId: 2,
  },
  {id:52,
    name: "Bosome Freho",
    abbrv: "",
    regionId: 2,
  },
  {id:53,
    name: "Bosomtwe",
    abbrv: "",
    regionId: 2,
  },
  {id:54,
    name: "Ejisu",
    abbrv: "",
    regionId: 2,
  },
  {id:55,
    name: "Ejura/Sekyedumase",
    abbrv: "",
    regionId: 2,
  },
  {id:56,
    name: "Juaben",
    abbrv: "",
    regionId: 2,
  },
  {id:57,
    name: "Kumasi",
    abbrv: "",
    regionId: 2,
  },
  {id:58,
    name: "Kwabre East",
    abbrv: "",
    regionId: 2,
  },
  {id:59,
    name: "Kwadaso",
    abbrv: "",
    regionId: 2,
  },
  {id:60,
    name: "Mampong",
    abbrv: "",
    regionId: 2,
  },
  {id:61,
    name: "Obuasi East",
    abbrv: "",
    regionId: 2,
  },
  {id:62,
    name: "Obuasi",
    abbrv: "",
    regionId: 2,
  },
  {id:63,
    name: "Offinso",
    abbrv: "",
    regionId: 2,
  },
  {id:64,
    name: "Offinso North",
    abbrv: "",
    regionId: 2,
  },
  {id:65,
    name: "Oforikrom",
    abbrv: "",
    regionId: 2,
  },
  {id:66,
    name: "Old Tafo",
    abbrv: "",
    regionId: 2,
  },
  {id:67,
    name: "Sekyere Afram Plains",
    abbrv: "",
    regionId: 2,
  },
  {id:68,
    name: "Sekyere Central",
    abbrv: "",
    regionId: 2,
  },
  {id:69,
    name: "Sekyere East",
    abbrv: "",
    regionId: 2,
  },
  {id:70,
    name: "Sekyere Kumawu",
    abbrv: "",
    regionId: 2,
  },
  {id:71,
    name: "Sekyere South",
    abbrv: "",
    regionId: 2,
  },
  {id:72,
    name: "Suame",
    abbrv: "",
    regionId: 2,
  },
];
