export const district = [
  {
   
    name: "Ablekuma Central",
    abbrv: "ABCMA",
    regionId: 1,
  },
  {
   
    name: "Ablekuma North",
    abbrv: "ABNMA",
    regionId: 1,
  },
  { name: "Ablekuma West", abbrv: "ABWMA", regionId: 1},
  {name: "Accra", abbrv: "ACCMA", regionId: 1},
  {  name: "Ada East", abbrv: "ADEMA", regionId: 1},
  { name: "Ada West", abbrv: "ADWMA", regionId: 1},
  { name: "Adenta", abbrv: "ADTMA", regionId: 1},
  {  name: "Ashaiman", abbrv: "ASHMA", regionId: 1},
  { name: "Ayawaso Central", abbrv: "AYCMA", regionId: 1},
  { name: "Ayawaso East", abbrv: "AYEMA", regionId: 1},
  { name: "Ayawaso North", abbrv: "AYNMA", regionId: 1},
  {  name: "Ayawaso West", abbrv: "AYWMA", regionId: 1},
  {  name: "Ga Central", abbrv: "GACMA", regionId: 1},
  {  name: "Ga East", abbrv: "GAEMA", regionId: 1},

  {  name: "Ga North", abbrv: "GANMA", regionId: 1},
  {  name: "Ga South", abbrv: "GASMA", regionId: 1},
  { name: "Ga West", abbrv: "GAWMA", regionId: 1},
  { name: "Korle-Klottey", abbrv: "KKLMA", regionId: 1},
  { name: "Kpone-Katamanso", abbrv: "KPKMA", regionId: 1},
  { name: "Krowor", abbrv: "KWRMA", regionId: 1},
  {  name: "La-Dade-Kotopon", abbrv: "LDKMA", regionId: 1},
  {  name: "La-Nkwantanang-Madina", abbrv: "LNMMA", regionId: 1},
  {  name: "Ledzokuku", abbrv: "LZKMA", regionId: 1},

  {  name: "Ningo-Prampram", abbrv: "NGPMA", regionId: 1},
  { name: "Okaikwei North", abbrv: "OKNMA", regionId: 1},
  {  name: "Shai-Osudoku", abbrv: "SHOMA", regionId: 1},
  { name: "Tema Metropolitan", abbrv: "TEMMA", regionId: 1},
  {  name: "Tema West", abbrv: "TMWMA", regionId: 1},
  {  name: "Weija Gbawe", abbrv: "WJGMA", regionId: 1},
  {  name: "Adansi Asokwa", abbrv: "ADKMA", regionId: 2 },
  { name: "Adansi North", abbrv: "ADNMA", regionId: 2 },
  {  name: "Adansi South", abbrv: "ADSMA", regionId: 2 },
  {  name: "Afigya-Kwabre North", abbrv: "AKNMA", regionId: 2 },
  {  name: "Afigya-Kwabre South", abbrv: "AKSMA", regionId: 2 },
  {  name: "Ahafo-Ano North", abbrv: "AANMA", regionId: 2 },
  { name: "Ahafo-Ano South East", abbrv: "ASEMA", regionId: 2 },
  { name: "Ahafo-Ano South West", abbrv: "ASWMA", regionId: 2 },
  {  name: "Akrofuom", abbrv: "AKFMA", regionId: 2 },
  {  name: "Amansie Central", abbrv: "AMCDA", regionId: 2 },
  {name: "Amansie West", abbrv: "AMWDA", regionId: 2 },
  {  name: "Amansie South", abbrv: "AMSDA", regionId: 2 },
  {  name: "Asante-Akim Central", abbrv: "AACMA", regionId: 2 },
  {  name: "Asante-Akim North", abbrv: "AANDA", regionId: 2 },
  { name: "Asante-Akim South", abbrv: "AASDA", regionId: 2 },
  {  name: "Asokore-Mampong", abbrv: "ASMDA", regionId: 2 },
  {  name: "Asokwa", abbrv: "ASKMA", regionId: 2 },
  { name: "Atwima-Kwanwoma", abbrv: "ATKMA", regionId: 2 },
  {  name: "Atwima-Mponua", abbrv: "ATMMA", regionId: 2 },
  { name: "Atwima-Nwabiagya", abbrv: "ATNMA", regionId: 2 },
  {  name: "Atwima-Nwabiagya North", abbrv: "ANNMA", regionId: 2 },
  {  name: "Bekwai", abbrv: "BEKMA", regionId: 2 },
  { name: "Bosome Freho", abbrv: "BSFMA", regionId: 2 },
  { name: "Bosomtwe", abbrv: "BSTMA", regionId: 2 },
  {  name: "Ejisu", abbrv: "EJSMA", regionId: 2 },
  {  name: "Ejura/Sekyedumase", abbrv: "EJRMA", regionId: 2 },
  {  name: "Juaben", abbrv: "JBNMA", regionId: 2 },
  {  name: "Kumasi", abbrv: "KSIMA", regionId: 2 },
  { name: "Kwabre East", abbrv: "KWEMA", regionId: 2 },
  { name: "Kwadaso", abbrv: "KWDMA", regionId: 2 },
  {  name: "Mampong", abbrv: "MPGMA", regionId: 2 },
  { name: "Obuasi East", abbrv: "OBEMA", regionId: 2 },
  {  name: "Obuasi", abbrv: "OBSMA", regionId: 2 },
  {  name: "Offinso", abbrv: "OFSMA", regionId: 2 },
  {  name: "Offinso North", abbrv: "OFNMA", regionId: 2 },
  {  name: "Oforikrom", abbrv: "OFKMA", regionId: 2 },
  {  name: "Old Tafo", abbrv: "OTFMA", regionId: 2 },
  {  name: "Sekyere Afram Plains", abbrv: "SAPMA", regionId: 2 },
  {  name: "Sekyere Central", abbrv: "SYCMA", regionId: 2 },
  { name: "Sekyere East", abbrv: "SYEMA", regionId: 2 },
  {  name: "Sekyere Kumawu", abbrv: "SYKMA", regionId: 2 },
  {  name: "Sekyere South", abbrv: "SYSMA", regionId: 2 },
  {  name: "Suame", abbrv: "SMEMA", regionId: 2 },


  {  name: "Banda District", abbrv: "BADA", regionId: 3 },
  {  name: "Berekum East", abbrv: "SMEMA", regionId: 3 },
  {  name: "Dormaa Central Municipal", abbrv: "DCMA", regionId: 3 },
  {  name: "Dormaa East District", abbrv: "DEDA", regionId: 3 },
  {  name: "Dormaa West District", abbrv: "DWDA", regionId: 3 },
  {  name: "Jaman North District", abbrv: "JNDA", regionId: 3 },
  {  name: "Jaman South Municipal", abbrv: "JSDA", regionId: 3 },
  {  name: "Sunyani Municipal", abbrv: "SYMA", regionId: 3 },
  {  name: "Sunyani West Municipal", abbrv: "SYWMA", regionId: 3 },
  {  name: "Tain District", abbrv: "TANDA", regionId: 3 },
  {  name: "Wenchi Municipal", abbrv: "WCMA", regionId: 3 },
  {  name: "Berekum West District", abbrv: "BWDA", regionId: 3 },



  {  name: "Atebubu Amantin Municipal", abbrv: "AAMA", regionId: 4 },
  {  name: "Kintampo North Municipal", abbrv: "KNMA", regionId: 4 },
  {  name: "Kintampo South District", abbrv: "KSDA", regionId: 4 },
  {  name: "Nkoranza South Municipal", abbrv: "NSMA", regionId: 4 },
  {  name: "Nkoranza North District", abbrv: "NNMA", regionId: 4 },
  {  name: "Pru East District", abbrv: "PEDA", regionId: 4 },
  {  name: "Sene East District", abbrv: "SEDA", regionId: 4 },
  {  name: "Sene West District", abbrv: "SWDA", regionId: 4 },
  {  name: "Techiman Municipal", abbrv: "TMMA", regionId: 4 },
  {  name: "Techiman North District", abbrv: "TNDA", regionId: 4 },
  {  name: "Pru West District", abbrv: "PWDA", regionId: 4 },

  

  {  name: "Abura Asebu Kwamankese District", abbrv: "AAKDA", regionId: 5 },
  {  name: "Agona East District", abbrv: "AGEDA", regionId: 5 },
  {  name: "Agona West Municipal", abbrv: "AGWDA", regionId: 5 },
  {  name: "Ajumako Enyan Essiam District", abbrv: "AEEDA", regionId: 5 },
  {  name: "Asikuma Odoben Brankwa District", abbrv: "AOBDA", regionId: 5 },
  {  name: "Assin Foso Municipal", abbrv: "ASFMA", regionId: 5 },
  {  name: "Assin South District", abbrv: "ASSDA", regionId: 5 },
  {  name: "Awutu Senya East Municipal", abbrv: "ASEMA", regionId: 5 },
  {  name: "Awutu Senya West District", abbrv: "ASWDA", regionId: 5 },
  {  name: "Cape Coast Metropolitan", abbrv: "CCMA", regionId: 5 },
  {  name: "Effutu Municipal", abbrv: "EFFMA", regionId: 5 },
  {  name: "Ekumfi District", abbrv: "EKFDA", regionId: 5 },
  {  name: "Gomoa Central District", abbrv: "GOCDA", regionId: 5 },
  {  name: "Gomoa West District", abbrv: "GOWDA", regionId: 5 },
  {  name: "Komenda Edina Eguafo Abirem Municipal", abbrv: "KEEAMA", regionId: 5 },
  {  name: "Mfantseman Municipal", abbrv: "MFMMA", regionId: 5 },
  {  name: "Twifo Atti Morkwa District", abbrv: "TAMDA", regionId: 5 },
  {  name: "Twifo Heman Lower Denkyira District", abbrv: "THLDDA", regionId: 5 },
  {  name: "Upper Denkyira East Municipal", abbrv: "UDEMA", regionId: 5 },
  {  name: "Upper Denkyira West District", abbrv: "UDWDA", regionId: 5 },
  {  name: "Assin North District", abbrv: "ASNDA", regionId: 5 },
  {  name: "Gomoa East District", abbrv: "GMEDA", regionId: 5 },


];
